local h = love.harmony.utils or error()

--- line `n` of a project's file, as the editor saved it
local function saved_line(project, file, n)
  local path = FS.join_path(
    love.harmony.tmpdir, 'projects', project, file)
  return string.lines(FS.read(path) or '')[n]
end

local function editor()
  scenario('open-close', function(wait)
    wait(.1)
    h.love_text('project("create")')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.love_text('edit()')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('open')
    wait(1)
    h.love_key('C-S-s')
    wait(.1)
    h.release_keys()

    wait(.1)
    h.love_text('list_contents()')
    wait(.1)
    h.love_key('return')
    wait(1)
    h.love_key('C-q')
    wait(.2)

    hm_done('edit')
  end)

  scenario('search', function(wait)
    wait(.1)
    h.love_text('project("turtle")')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.love_text('edit()')
    wait(.1)
    h.love_key('return')
    wait(.2)
    h.love_key('C-f')
    wait(.1)
    h.release_keys()
    h.screenshot('symbols')
    wait(.2)
    h.love_key('down')
    wait(.01)
    h.love_key('down')
    wait(.01)
    h.love_key('down')
    h.screenshot('symbols-2')

    wait(.1)
    h.love_text('draw')
    h.screenshot('symbols-3')
    wait(.5)
    h.love_key('backspace')
    wait(.01)
    h.love_key('backspace')
    wait(.01)
    h.love_key('backspace')
    wait(.01)
    h.love_key('backspace')
    wait(.2)
    h.love_text('tx')
    h.screenshot('symbols-4')
    wait(.2)

    h.love_key('return')
    wait(1)
    h.love_key('S-escape')
    wait(1)

    hm_done()
  end)

  scenario('add', function(wait)
    wait(.1)
    h.love_text('project("test-add")')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.love_text('edit()')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.love_text('for i=1,5 do print(i) end')
    wait(.1)
    h.screenshot('input')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.screenshot('added')
    wait(.1)
    h.love_key('up')
    wait(.1)
    h.screenshot('sel-up')
    wait(.2)
    h.love_key('S-return')
    h.screenshot('newline')

    wait(1)
    h.love_key('S-escape')
    wait(.1)
    h.release_keys()
    wait(.1)

    hm_done()
  end)

  scenario('change', function(wait)
    wait(.1)
    h.love_text('clone("turtle", "turtlemod")')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('clone')

    wait(.1)
    h.love_text('project("turtlemod")')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.love_text('edit("drawing.lua")')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('open')
    wait(.2)
    h.love_key(h.shortcuts.toggle)

    wait(2)

    wait(.1)
    h.screenshot('before')
    wait(.2)
    h.love_key(h.shortcuts.toggle)
    wait(.2)
    h.love_key('C-home')
    wait(.1)
    h.release_keys()
    wait(.1)
    h.screenshot('start')

    wait(.2)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.screenshot('sel-down')
    wait(.1)
    h.love_key('pagedown')
    wait(.1)
    h.screenshot('scroll-down')

    wait(.1)
    h.love_key('C-f')
    wait(.01)
    h.release_keys()
    wait(.1)
    h.love_text('body')
    wait(.01)
    h.love_key('return')

    wait(.1)
    h.love_key('return')
    wait(.1)
    h.love_key('end')
    wait(.1)
    h.love_key('backspace')
    wait(.02)
    h.love_key('backspace')
    wait(.02)
    h.love_key('backspace')
    wait(.02)
    h.love_key('backspace')
    wait(.02)
    h.love_key('backspace')

    wait(.1)
    h.love_text('red')
    wait(.01)
    h.love_key('return')

    wait(.1)
    h.screenshot('edited')
    assert(saved_line('turtlemod', 'drawing.lua', 2)
      == 'body_color = Color.red')
    wait(.2)
    h.love_key(h.shortcuts.toggle)
    wait(.1)
    h.screenshot('after')

    wait(.4)
    h.love_key(h.shortcuts.toggle)
    wait(.1)
    h.love_key('C-f')
    wait(.01)
    h.release_keys()
    wait(.1)
    h.love_text('body')
    wait(.01)
    h.love_key('return')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.love_key('end')
    wait(.1)
    h.love_key('backspace')
    wait(.02)
    h.love_key('backspace')
    wait(.02)
    h.love_key('backspace')
    wait(.02)
    wait(.1)
    h.love_text('blue')
    wait(.01)
    h.love_key('return')

    wait(.1)
    h.screenshot('edited-2')
    assert(saved_line('turtlemod', 'drawing.lua', 2)
      == 'body_color = Color.blue')
    wait(.2)
    h.love_key(h.shortcuts.toggle)
    wait(.1)
    h.screenshot('after-2')

    wait(1)
    h.love_key('C-q')
    wait(.1)
    h.release_keys()
    wait(.1)

    hm_done()
  end)

  scenario('move', function(wait)
    wait(.1)
    h.love_text('project("turtle")')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.love_text('edit("action.lua")')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('open')

    wait(.2)
    h.love_key('up')
    wait(.1)
    h.love_key('up')
    wait(.1)
    h.love_key('up')
    wait(.1)
    h.screenshot('sel-up')
    wait(.1)
    h.love_key('up')
    wait(.1)
    h.love_key('up')

    wait(.1)
    h.love_key('C-m')
    wait(.01)
    h.release_keys()
    wait(.1)
    h.screenshot('move-start')
    wait(.1)
    h.love_key('pageup')
    wait(.1)
    h.screenshot('scroll-up')
    wait(.1)
    h.love_key('up')
    wait(.1)
    h.love_key('up')
    wait(.1)
    h.screenshot('move-up')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('move-done')

    wait(.1)
    h.love_key('down')
    wait(.2)
    h.love_key('S-return')
    h.screenshot('newline')

    wait(1)
    h.love_key('S-escape')
    wait(.1)
    h.release_keys()
    wait(.1)
    hm_done()
  end)

  scenario('delete', function(wait)
    wait(.1)
    h.love_text('project("turtle")')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.love_text('edit("main.lua")')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('open')

    wait(.2)
    h.love_key('pageup')
    wait(.1)
    h.love_key('pageup')
    wait(.1)
    h.love_key('pageup')
    wait(.1)
    h.screenshot('up')

    wait(.2)
    h.love_key('C-home')
    wait(.1)
    h.release_keys()
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.screenshot('move-down')

    wait(.1)
    h.love_key('escape')
    wait(.1)
    h.screenshot('load')
    wait(.1)
    h.love_key('C-w')
    wait(.1)
    h.release_keys()
    wait(.1)
    h.screenshot('wipe')
    wait(.1)
    h.love_key('C-y')
    wait(.1)
    h.release_keys()
    wait(.1)
    h.screenshot('delete')

    wait(.3)
    h.love_text('incr = 20')
    wait(.1)
    h.screenshot('input')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('added')


    wait(.2)
    h.love_key('C-w')
    wait(.1)
    h.release_keys()
    wait(.1)
    h.love_key('S-return')
    wait(.1)
    h.screenshot('newline')


    wait(1)
    h.love_key('C-S-s')
    wait(.1)
    h.release_keys()
    wait(.1)
    h.screenshot('leave')

    wait(.1)
    h.love_text('print("let\'s check back")')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('msg')

    wait(.1)
    h.love_key('up')
    wait(.1)
    h.screenshot('history-1')
    wait(.1)
    h.love_key('up')
    wait(.1)
    h.screenshot('history-2')
    wait(.1)
    h.love_key('return')
    wait(.2)
    h.love_key('C-home')
    wait(.1)
    h.release_keys()
    wait(.1)
    h.screenshot('reopen')

    wait(1)
    h.love_key('S-escape')
    wait(.1)
    h.release_keys()
    wait(.1)
    h.screenshot('exit')

    wait(.1)
    hm_done()
  end)

  scenario('follow', function(wait)
    wait(.1)
    h.love_text('project("turtle")')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.love_text('edit("drawing.lua")')
    wait(.1)
    h.love_key('return')

    wait(.1)
    h.love_key('C-f')
    wait(.01)
    h.release_keys()
    wait(.1)
    h.love_text('body')
    wait(.01)
    h.love_key('return')
    wait(.1)
    h.screenshot('find')

    wait(.1)
    h.love_key('escape')
    wait(.1)
    h.love_key('end')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.love_key('down')
    wait(.1)
    h.screenshot('sel-down')

    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('jump-back')

    wait(.1)
    h.love_key('C-pagedown')
    wait(.01)
    h.release_keys()
    wait(.1)
    h.screenshot('jump-end')

    wait(.1)
    h.love_key('down')
    wait(.1)
    h.screenshot('sel-offscreen')


    wait(.1)
    h.love_key('S-pageup')
    wait(.01)
    h.release_keys()
    wait(.1)
    h.screenshot('scroll-one-up')
    wait(.1)
    h.love_key('pageup')
    wait(.1)
    h.screenshot('scroll-up')

    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('loaded-protect')

    wait(1)
    --- the first leaves the open block, the second the editor
    h.love_key('S-escape')
    wait(.1)
    h.love_key('S-escape')
    wait(.1)
    h.release_keys()
    wait(.1)

    hm_done()
  end)
end

editor()
