local h = love.harmony.utils or error()

local function examples()
  scenario('sine', function(wait)
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.love_text('run("sine")')
    wait(.1)
    h.love_key('return')

    wait(.5)
    h.screenshot('sine')
    wait(.1)
    -- a project with no update loop leaves through Ctrl+Q
    h.love_key('C-q')
    wait(.3)

    hm_done()
  end)

  -- Space cycles the digits' color, Shift+Space the background,
  -- Shift+R reads the clock again, P pauses.
  scenario('clock', function(wait)
    wait(.1)
    h.love_text('run("clock")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    assert(love.state.app_state == 'running')
    h.screenshot('clock')
    wait(.2)
    h.love_key('space')
    wait(.2)
    h.screenshot('space')
    wait(.2)
    -- shift stays held until release_keys
    h.love_key('S-space')
    wait(.2)
    h.screenshot('shift-space')
    wait(.2)
    h.love_key('S-r')
    wait(.2)
    h.screenshot('shift-r')
    wait(.2)
    h.release_keys()
    h.love_key('p')
    wait(.3)
    assert(love.state.app_state == 'inspect')
    h.screenshot('paused')
    wait(.2)
    -- a paused project leaves through Ctrl+Q, and Enter clears
    -- the pause message from the console
    h.love_key('C-q')
    wait(.3)
    h.release_keys()
    h.love_key('return')
    wait(.2)
    hm_done()
  end)

  -- Space switches between the color list and the picture.
  scenario('colors', function(wait)
    wait(.1)
    h.love_text('run("colors")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    assert(love.state.app_state == 'running')
    h.screenshot('list')
    wait(.2)
    h.love_key('space')
    wait(.3)
    h.screenshot('picture')
    wait(.2)
    h.love_key('space')
    wait(.3)
    h.screenshot('list-again')
    wait(.2)
    h.love_key('C-s')
    wait(.3)
    hm_done()
  end)

  -- Minus and equals change the speed, a drag up is one step
  -- faster, R starts a new grid.
  scenario('life', function(wait)
    wait(.1)
    h.love_text('run("life")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    assert(love.state.app_state == 'running')
    h.screenshot('life')
    wait(.2)
    -- love_key splits chords at '-', so minus goes as events
    h.love_event('keypressed', '-')
    h.love_event('keyreleased', '-')
    wait(.2)
    h.screenshot('slower')
    wait(.1)
    h.love_key('=')
    wait(.1)
    h.love_key('=')
    wait(.2)
    h.screenshot('faster')
    wait(.1)
    h.love_event('mousepressed', 512, 300, 1)
    wait(.1)
    h.love_event('mousereleased', 512, 260, 1)
    wait(.2)
    h.screenshot('dragged')
    wait(.1)
    h.love_key('r')
    wait(.2)
    h.screenshot('reset')
    wait(.1)
    h.love_key('C-s')
    wait(.3)
    hm_done()
  end)

  -- E picks the easy opponent, Space starts, the mouse moves the
  -- left paddle, R goes back to the start screen.
  scenario('pong', function(wait)
    local function move_paddle(dy, times)
      for _ = 1, times do
        h.love_event('mousemoved', 100, 300, 0, dy, false)
      end
    end
    wait(.1)
    h.love_text('run("pong")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    assert(love.state.app_state == 'running')
    h.screenshot('pong')
    wait(.1)
    h.love_key('e')
    wait(.2)
    h.screenshot('easy')
    wait(.1)
    h.love_key('space')
    wait(.5)
    h.screenshot('play')
    wait(.1)
    move_paddle(-20, 6)
    wait(.2)
    h.screenshot('paddle-up')
    wait(.1)
    move_paddle(20, 12)
    wait(.2)
    h.screenshot('paddle-down')
    wait(3)
    h.screenshot('later')
    wait(.1)
    h.love_key('r')
    wait(.3)
    h.screenshot('reset')
    wait(.1)
    h.love_key('C-s')
    wait(.3)
    hm_done()
  end)

  -- A wrong guess, text the validator refuses, two more guesses.
  scenario('guess', function(wait)
    local function guess(text)
      h.love_text(text)
      wait(.2)
      h.love_key('return')
      wait(.3)
    end
    wait(.1)
    h.love_text('run("guess")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    h.screenshot('guess')
    wait(.1)
    guess('50')
    h.screenshot('fifty')
    wait(.1)
    h.love_text('x')
    wait(.3)
    h.screenshot('refused')
    wait(.1)
    h.love_key('backspace')
    wait(.2)
    guess('25')
    guess('75')
    h.screenshot('more')
    wait(.1)
    h.love_key('C-q')
    wait(.3)
    hm_done()
  end)

  -- With no board attached a line is refused by the port; Up and
  -- Down walk through what was sent.
  scenario('terminal', function(wait)
    wait(.1)
    h.love_text('run("terminal")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    assert(love.state.app_state == 'running')
    h.screenshot('terminal')
    wait(.1)
    h.love_text('print(1)')
    wait(.2)
    h.love_key('return')
    wait(.4)
    h.screenshot('sent')
    wait(.1)
    h.love_text('x = 2')
    wait(.2)
    h.love_key('return')
    wait(.4)
    h.love_key('up')
    wait(.3)
    h.screenshot('recall')
    wait(.1)
    h.love_key('up')
    wait(.3)
    h.screenshot('recall-more')
    wait(.1)
    h.love_key('down')
    wait(.3)
    h.screenshot('recall-down')
    wait(.1)
    h.love_key('C-s')
    wait(.3)
    hm_done()
  end)

  scenario('turtle', function(wait)
    wait(.1)
    local rt = 'run("turtle")'
    h.love_text(rt)
    wait(.1)
    -- wait(.1)
    h.love_key('return')
    wait(.3)
     assert(love.state.app_state == 'running')
    h.screenshot('turtl')
    wait(.3)
    h.love_key('space')
    wait(.1)
    love.harmony.timer:script(function(wait)
      h.love_key('i')
      wait(.1)
      h.love_text('b')
      wait(.5)
      h.love_key('return')
      wait(.2)
    end)

    wait(1)
    h.screenshot('moved')
    wait(.1)
    h.love_key('C-s')
    wait(.3)
    hm_done()
  end)

  -- Left click steps to the next example, right click picks one
  -- at random; an edited body runs on Enter, Escape takes back
  -- what was not submitted.
  scenario('tixy', function(wait)
    local function click(button)
      h.love_event('mousepressed', 200, 200, button)
      h.love_event('mousereleased', 200, 200, button)
    end
    wait(.1)
    h.love_text('run("tixy")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    assert(love.state.app_state == 'running')
    h.screenshot('tixy')
    wait(.1)
    click(1)
    wait(.3)
    h.screenshot('next')
    wait(.1)
    click(2)
    wait(.3)
    h.screenshot('random')
    wait(.1)
    h.love_text(' * -1')
    wait(.2)
    h.love_key('return')
    wait(.3)
    h.screenshot('edited')
    wait(.1)
    h.love_text('+')
    wait(.2)
    h.love_key('escape')
    wait(.3)
    h.screenshot('reverted')
    wait(.1)
    h.love_key('C-s')
    wait(.3)
    hm_done()
  end)

  -- The tools in the console, with no board plugged in: what the
  -- firmware file holds, and upload refusing.
  scenario('microbit', function(wait)
    local function console(text)
      h.love_text(text)
      wait(.2)
      h.love_key('return')
      wait(.5)
    end
    wait(.1)
    console('run("microbit")')
    h.screenshot('microbit')
    wait(.1)
    console('require("tools")')
    h.screenshot('tools')
    wait(.1)
    console('hexmap()')
    h.screenshot('hexmap')
    wait(.1)
    console('upload()')
    h.screenshot('upload')
    wait(.1)
    h.love_key('C-q')
    wait(.3)
    hm_done()
  end)

  scenario('repl', function(wait)
    wait(.1)
    h.love_text('run("repl")')
    wait(.1)
    h.love_key('return')
    wait(.3)
    h.love_text('repl')
    wait(.3)
    h.love_key('return')

    for i = 0, 25 do
      wait(.1)
      h.love_text(string.char(i + 97))
      wait(.3)
      h.love_key('return')
    end

    wait(1)
    h.screenshot('repl')
    wait(.1)
    h.love_key('C-q')
    wait(.3)
    hm_done()
  end)

  scenario('valid', function(wait)
    wait(.1)
    h.love_text('run("valid")')
    wait(.1)
    h.love_key('return')
    wait(.3)
    h.love_text('repl')
    wait(.3)
    h.love_key('return')
    wait(.3)
    h.screenshot('valid')
    wait(.1)
    h.love_text('ABC')
    wait(.3)
    h.love_key('return')
    wait(.3)
    h.screenshot('refused')
    wait(.1)
    h.love_key('C-q')
    wait(.3)
    hm_done()
  end)
end

examples()
