local h = love.harmony.utils or error()

local function examples()
  scenario('sine', function(wait)
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.love_text('run("sine")')
    wait(.1)
    h.love_key('return')

    wait(.5)
    h.screenshot('sine')
    h.love_key('C-S-q')
    wait(.3)

    hm_done()
  end)

  -- Space cycles the digits' color, Shift+Space the background,
  -- Shift+R reads the clock again, P pauses.
  scenario('clock', function(wait)
    wait(.1)
    h.love_text('run("clock")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    assert(love.state.app_state == 'running')
    h.screenshot('clock')
    wait(.2)
    h.love_key('space')
    wait(.2)
    h.screenshot('space')
    wait(.2)
    -- shift stays held until release_keys
    h.love_key('S-space')
    wait(.2)
    h.screenshot('shift-space')
    wait(.2)
    h.love_key('S-r')
    wait(.2)
    h.screenshot('shift-r')
    wait(.2)
    h.release_keys()
    h.love_key('p')
    wait(.3)
    assert(love.state.app_state == 'inspect')
    h.screenshot('paused')
    wait(.2)
    -- a paused project leaves through Ctrl+Q, and Enter clears
    -- the pause message from the console
    h.love_key('C-q')
    wait(.3)
    h.release_keys()
    h.love_key('return')
    wait(.2)
    hm_done()
  end)

  -- Space switches between the color list and the picture.
  scenario('colors', function(wait)
    wait(.1)
    h.love_text('run("colors")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    assert(love.state.app_state == 'running')
    h.screenshot('list')
    wait(.2)
    h.love_key('space')
    wait(.3)
    h.screenshot('picture')
    wait(.2)
    h.love_key('space')
    wait(.3)
    h.screenshot('list-again')
    wait(.2)
    h.love_key('C-s')
    wait(.3)
    hm_done()
  end)

  -- Minus and equals change the speed, a drag up is one step
  -- faster, R starts a new grid.
  scenario('life', function(wait)
    wait(.1)
    h.love_text('run("life")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    assert(love.state.app_state == 'running')
    h.screenshot('life')
    wait(.2)
    -- love_key splits chords at '-', so minus goes as events
    h.love_event('keypressed', '-')
    h.love_event('keyreleased', '-')
    wait(.2)
    h.screenshot('slower')
    wait(.1)
    h.love_key('=')
    wait(.1)
    h.love_key('=')
    wait(.2)
    h.screenshot('faster')
    wait(.1)
    h.love_event('mousepressed', 512, 300, 1)
    wait(.1)
    h.love_event('mousereleased', 512, 260, 1)
    wait(.2)
    h.screenshot('dragged')
    wait(.1)
    h.love_key('r')
    wait(.2)
    h.screenshot('reset')
    wait(.1)
    h.love_key('C-s')
    wait(.3)
    hm_done()
  end)

  -- E picks the easy opponent, Space starts, the mouse moves the
  -- left paddle, R goes back to the start screen.
  scenario('pong', function(wait)
    local function move_paddle(dy, times)
      for _ = 1, times do
        h.love_event('mousemoved', 100, 300, 0, dy, false)
      end
    end
    wait(.1)
    h.love_text('run("pong")')
    wait(.1)
    h.love_key('return')
    wait(.5)
    assert(love.state.app_state == 'running')
    h.screenshot('pong')
    wait(.1)
    h.love_key('e')
    wait(.2)
    h.screenshot('easy')
    wait(.1)
    h.love_key('space')
    wait(.5)
    h.screenshot('play')
    wait(.1)
    move_paddle(-20, 6)
    wait(.2)
    h.screenshot('paddle-up')
    wait(.1)
    move_paddle(20, 12)
    wait(.2)
    h.screenshot('paddle-down')
    wait(3)
    h.screenshot('later')
    wait(.1)
    h.love_key('r')
    wait(.3)
    h.screenshot('reset')
    wait(.1)
    h.love_key('C-s')
    wait(.3)
    hm_done()
  end)

  scenario('turtle', function(wait)
    wait(.1)
    local rt = 'run("turtle")'
    h.love_text(rt)
    wait(.1)
    -- wait(.1)
    h.love_key('return')
    wait(.3)
     assert(love.state.app_state == 'running')
    h.screenshot('turtl')
    wait(.3)
    h.love_key('space')
    wait(.1)
    love.harmony.timer:script(function(wait)
      h.love_key('i')
      wait(.1)
      h.love_text('b')
      wait(.5)
      h.love_key('return')
      wait(.2)
    end)

    wait(1)
    h.love_key('C-S-q')
    wait(.1)
    hm_done()
  end)

  scenario('repl', function(wait)
    wait(.1)
    h.love_text('run("repl")')
    wait(.1)
    h.love_key('return')
    wait(.3)
    h.love_text('repl')
    wait(.3)
    h.love_key('return')

    for i = 0, 25 do
      wait(.1)
      h.love_text(string.char(i + 97))
      wait(.3)
      h.love_key('return')
    end

    wait(1)
    h.love_key('C-S-q')
    wait(.1)
    hm_done()
  end)

  scenario('valid', function(wait)
    wait(.1)
    h.love_text('run("valid")')
    wait(.1)
    h.love_key('return')
    wait(.3)
    h.love_text('repl')
    wait(.3)
    h.love_key('return')

    wait(1)
    h.love_key('C-S-q')
    wait(1)
    hm_done()
  end)
end

examples()
