local h = love.harmony.utils or error()

local function inspect()
  scenario('turtle', function(wait)
    wait(.1)
    h.love_text('run("turtle")')
    wait(.1)
    h.love_key('return')

    h.screenshot('running')
    wait(.3)
    h.love_key('C-pause')
    wait(.1)
    h.release_keys()
    wait(.1)
    h.screenshot('paused')

    wait(.1)
    h.love_key('space')
    wait(.1)
    h.screenshot('console')
    wait(.4)
    h.love_text('tx = 50')
    wait(.1)
    h.screenshot('console-with-text')
    wait(.1)
    h.love_key('return')
    wait(.4)
    h.love_text('ty = 100')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('console-emptied')

    wait(.4)
    h.love_text('continue()')
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.screenshot('modified')

    wait(1)
    h.love_key('C-q')
    wait(.1)
    hm_done()
  end)
end

inspect()
