local h = love.harmony.utils or error()

local function scratch()
  scenario('startup-scratch', function(wait)
    wait(.3)
    assert(love.state.app_state == 'ready')
    h.love_text('current_project()')
    h.love_key('return')
    wait(.2)
    h.screenshot('startup-scratch')
    hm_done()
  end)

  scenario('close-redirect', function(wait)
    h.love_text('project("clock")')
    h.love_key('return')
    wait(.3)
    h.love_text('close_project()')
    h.love_key('return')
    wait(.3)
    h.love_text('current_project()')
    h.love_key('return')
    wait(.2)
    h.screenshot('close-redirect')
    hm_done()
  end)

  scenario('env-reset-on-switch', function(wait)
    h.love_text('qqq = 42')
    h.love_key('return')
    wait(.2)
    h.love_text('project("turtle")')
    h.love_key('return')
    wait(.3)
    h.love_text('print(qqq)')
    h.love_key('return')
    wait(.2)
    h.screenshot('env-reset')
    hm_done()
  end)

  scenario('scratch-persists-files', function(wait)
    h.love_text('writefile("keep.txt", "data")')
    h.love_key('return')
    wait(.2)
    h.love_text('print(readfile("keep.txt"))')
    h.love_key('return')
    wait(.2)
    h.screenshot('scratch-files')
    hm_done()
  end)

  scenario('reset-scratch', function(wait)
    h.love_text('writefile("extra.lua", "--")')
    h.love_key('return')
    wait(.2)
    h.love_text('reset_scratch()')
    h.love_key('return')
    wait(.3)
    h.love_text('list_contents()')
    h.love_key('return')
    wait(.2)
    h.screenshot('reset-scratch')
    hm_done()
  end)

  scenario('console-print-idle', function(wait)
    h.love_text('print("1")')
    h.love_key('return')
    wait(.2)
    h.screenshot('console-idle')
    hm_done()
  end)
end

scratch()
